server:
  port: 8085
  servlet:
    context-path: /

spring:
  application:
    name: PAYMENT-SERVICE

management:
  server:
    port: 8085
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true