version: "3"

services:
  
  patient-db:
    image: 'postgres:latest'
    container_name: patient-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patient
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d patient"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
