name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build_services:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d --build
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pytest
        run: pip install pytest
      - name: Install requests
        run: pip install requests
      - name: sleep
        run: sleep 65
      - name: Run tests
        run: pytest 
      - name: sleep
        run: sleep 15
      - name: Stop containers
        if: always()
        run: docker-compose down
